# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    # Run a PowerShell script to generate Markdown files from your module
    # Note: Ubuntu environments on ReadTheDocs usually have pwsh pre-installed,
    # or you can download it in a pre_install step if needed.
    pre_build:
      - pwsh -Command "& ./docs/Generate-Docs.ps1"

# We are using MkDocs to build the site from the generated Markdown
mkdocs:
  configuration: mkdocs.yml

python:
  install:
    # Install MkDocs and any themes (like mkdocs-material) via pip
    - requirements: docs/requirements.txt
